---
title: "Write up on grades"
author: "JP"
date: "12/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Prep

```{r}
library(tidyverse)
library(tidymodels)

theme_set(theme_light())
options(scipen = 9999)

year_function <- function(name, year){
  link <- glue::glue("cpp_data/gpa_equity_gap/{name}{year}.csv")
  read_csv(link)
}
```


```{r}
psy_soc <- fs::dir_ls(here::here("cpp_data"),
                           glob = "*.csv")

psy_soc_combined <-map_dfr(psy_soc, read_csv)

psy_soc <- fs::dir_ls(here::here("cpp_data"),
                           glob = "*.csv")

psysoc <-map_dfr(psy_soc, read_csv) %>% 
  janitor::clean_names()
head(psysoc)

first_gen <- map_df(11:20, ~year_function(name = "firstgen", year = .x)) %>% 
  janitor::clean_names()
head(first_gen)

race_enroll <- map_df(11:20, ~year_function(name = "eth_enroll", year = .x)) %>% 
  janitor::clean_names()
head(race_enroll)

race_gpa <- map_df(11:20, ~year_function(name = "eth_gpa", year = .x)) %>% 
  janitor::clean_names()
head(race_gpa)

gender <- map_df(11:20, ~year_function(name = "gender", year = .x)) %>% 
  janitor::clean_names()
head(gender)
```

```{r}
psysoc <- psysoc %>% 
  separate(col = "year_term", into = c("year", "term"), sep = " - ") %>% 
  separate(col = "course_code", into = c("department", "course_number"), sep = 3) %>% 
  mutate(non_passing_rate = str_remove_all(non_passing_rate, "%"),
         non_passing_rate = as.numeric(non_passing_rate),
         non_passing_rate = non_passing_rate/100)

first_gen <- first_gen %>% 
  separate(col = "course_code", into = c("department", "course_number"), sep = 3) %>% 
  rename(course_title = course)

race_enroll <- race_enroll %>% 
  separate(col = "course_code", into = c("department", "course_number"), sep = 3) %>% 
  mutate(white_enroll = recode(white, "N<10" = "10"),
         black_enroll = recode(african_american, "N<10" = "10"),
         asian_enroll = recode(asian, "N<10" = "10")) %>%
  dplyr::select(-"data_download_for_which_courses_have_the_largest_gpa_equity_gaps", -"white", -"african_american", -"asian") %>% 
  rename(latino_enroll = latino_a,
         course_title = course)

race_gpa <- race_gpa %>% 
  separate(col = "course_code", into = c("department", "course_number"), sep = 3) %>%
  mutate(white_gpa = recode(white, "N<10" = NA_character_),
         black_gpa = recode(african_american, "N<10" = NA_character_),
         asian_gpa = recode(asian, "N<10" = NA_character_)) %>% 
  dplyr::select(-"white", -"african_american", -"asian") %>% 
  rename(latino_gpa = latino_a,
         course_title = course)

gender <- gender %>% 
  separate(col = "course_code", into = c("department", "course_number"), sep = 3) %>%
  mutate(male_enroll = recode(male_enrollment, "N<10" = NA_character_),
         male_gpa = recode(male_gpa, "N<10" = NA_character_),
         gpa_gap = recode(gpa_gap, "N/A" = NA_character_)) %>% 
  dplyr::select(-"male_enrollment") %>% 
  rename(course_title = course,
         female_enroll = female_enrollment)
```

```{r}
psysoc <- psysoc %>% 
  mutate(year = factor(year),
         term = factor(term),
         department = factor(department),
         course_number = factor(course_number))

first_gen <- first_gen %>% 
  dplyr::select(-x1) %>% 
  mutate(department = factor(department),
         course_number = factor(course_number),
         year = factor(year)) %>% 
  rename(gen_gpa_gap = gpa_gap)

gender <- gender %>% 
  dplyr::select(-x1) %>% 
  mutate(department = factor(department),
         course_number = factor(course_number),
         male_gpa = as.numeric(male_gpa),
         gpa_gap = as.numeric(gpa_gap),
         year = factor(year),
         male_enroll = as.numeric(male_enroll)) %>% 
  rename(gender_gpa_gap = gpa_gap)

race_enroll <- race_enroll %>% 
  dplyr::select(-x1) %>% 
  mutate(department = factor(department),
         course_number = factor(course_number),
         year = factor(year),
         white_enroll = as.numeric(white_enroll),
         black_enroll = as.numeric(black_enroll),
         asian_enroll = as.numeric(asian_enroll))

race_gpa <- race_gpa %>% 
  dplyr::select(-x1) %>% 
  mutate(department = factor(department),
         course_number = factor(course_number),
         year = factor(year),
         white_gpa = as.numeric(white_gpa),
         black_gpa = as.numeric(black_gpa),
         asian_gpa = as.numeric(asian_gpa))
```

```{r}
data <- left_join(psysoc, first_gen, by = c("year", "department", "course_number", "course_title")) %>% 
  left_join(gender, by = c("year", "department", "course_number", "course_title")) %>% 
  left_join(race_enroll, by = c("year", "department", "course_number", "course_title")) %>%
  left_join(race_gpa, by = c("year", "department", "course_number", "course_title")) %>% 
  rename(first_gen_enroll = first_gen_enrollment,
         non_first_gen_enroll = not_first_gen_enrollment)

data <- data %>% 
  mutate(year2 = as.numeric(year),
         term_type = case_when(year2 >= 9 ~ "Semester",
                               year2 < 9 ~ "Quarter")) %>% 
  filter(department == "PSY" |
           department == "SOC") %>% 
  filter(!str_detect(course_number, ("A|L")))

academic <- data %>% 
  filter(year != "2020" &
           year != "2021")
```

```{r}
data %>% 
  pivot_longer(cols = c(first_gen_enroll, non_first_gen_enroll,
                        female_enroll, male_enroll,
                        latino_enroll, white_enroll, black_enroll, asian_enroll),
               names_to = "enroll_types",
               values_to = "enroll_numbers") %>% 
  filter(term == "Academic Year") %>% 
  mutate(year_short = recode(year, "2011" = "11",
                             "2012" = "12", 
                             "2013" = "13",
                             "2014" = "14",
                             "2015" = "15",
                             "2016" = "16",
                             "2017" = "17",
                             "2018" = "18",
                             "2019" = "19",
                             "2020" = "20",
                             "2021" = "21")) %>%
  drop_na(non_passing_rate) %>% 
  ggplot(aes(course_number, non_passing_rate)) + 
  geom_text(aes(color = year_short, label = year_short), 
            size = 4) +
  facet_wrap(~term_type, scales = "free") +
  coord_flip() +
  theme(legend.position = "none")

data %>% 
  filter(term == "Academic Year") %>% 
    mutate(year_short = recode(year, "2011" = "11",
                             "2012" = "12", 
                             "2013" = "13",
                             "2014" = "14",
                             "2015" = "15",
                             "2016" = "16",
                             "2017" = "17",
                             "2018" = "18",
                             "2019" = "19",
                             "2020" = "20",
                             "2021" = "21"),
           impact_n = cut(impact, breaks = 4)) %>%
  # filter(impact_n != 1) %>% 
  ggplot(aes(course_number, impact)) + 
  geom_text(aes(color = department, label = year_short), 
            size = 4) +
  facet_wrap(~impact_n, scales = "free") +
  coord_flip() +
  theme(legend.title = element_blank())

data %>% 
  filter(course_number == 2201 |
           course_number == 2204 |
           course_number == 2210 |
           course_number == 2222 |
           course_number == 3307 |
           course_number == 4433 |
           course_number == 4611 |
           course_number == 201 |
           course_number == 204 |
           course_number == 210 |
           course_number == 307 |
           course_number == 433 |
           course_number == 498) %>% 
  mutate(course_number = recode(course_number, "2201" = "Introduction-S",
                                "2204" = "Research Methods-S",
                                "2210" = "Mind, Brain, Behavior-S",
                                "2222" = "Careers-S",
                                "3307" = "Statistics-S",
                                "4433" = "Experimental-S",
                                "4611" = "Senior Symposium-S",
                                "201" = "Introduction-Q",
                                "204" = "Research Methods-Q",
                                "210" = "Mind, Brain, Behavior-Q",
                                "307" = "Statistics-Q",
                                "433" = "Experimental-Q",
                                "498" = "Senior Symposium-Q"),
         year_short = recode(year, "2011" = "11",
                             "2012" = "12", 
                             "2013" = "13",
                             "2014" = "14",
                             "2015" = "15",
                             "2016" = "16",
                             "2017" = "17",
                             "2018" = "18",
                             "2019" = "19",
                             "2020" = "20",
                             "2021" = "21")) %>% 
  filter(department == "PSY") %>% 
  filter(term == "Academic Year") %>% 
  ggplot(aes(fct_reorder(course_number, non_passing_rate), non_passing_rate)) + 
  geom_text(aes(color = year_short, label = year_short), 
            size = 4,
            position = position_jitter(width = .3, seed = 405)) +
  coord_flip() +
  scale_color_manual(values = c("blue", "#884EA0", "#2471A3", "#17A589", "#D4AC0D", "#229954",
                                "#BAF10F", "#2E4053", "#CB4335", "#0FB7F1")) +
  labs(x = "",
       y = "Non-Passing Rate",
       title = "Non-passing rate for core Psychology classes",
       subtitle = "Comparisons between Quarter and Semester",
       caption = "Data gathered from Tableau resources from Cal Poly Pomona") +
  theme(legend.position = "none")
```

```{r}
set.seed(12222021)

# split <- initial_split(academic, prop = .8)

# train <- training(split)
# test <- testing(split)
```

```{r}
set.seed(12222021)

names(train)

recipe <- recipe(non_passing_rate ~ year + department + enrollment + course_number + 
                   first_gen_enroll + non_first_gen_enroll + first_gen_gpa + not_first_gen_gpa +
                   gen_gpa_gap +
                   female_enroll + female_gpa + male_gpa + gender_gpa_gap + male_enroll +
                   latino_enroll + white_enroll + black_enroll + asian_enroll +
                   latino_gpa + white_gpa + black_gpa + asian_gpa +
                   term_type,
                     data = train) %>% 
  step_zv(all_predictors(), -all_outcomes()) %>% 
  step_unknown(all_nominal()) %>% 
  step_novel(all_nominal()) %>% 
  step_dummy(all_nominal()) %>% 
  step_nzv(all_predictors()) %>%
  step_impute_mean(all_numeric(), -all_outcomes()) %>% 
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_nzv(all_predictors()) %>% 
  prep(training = train, retain = TRUE)

set.seed(12222021)

model <- linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode("regression") %>% 
  set_args(penalty = 0,
           mixture = 0)

flow <- workflow() %>% 
  add_recipe(recipe) %>% 
  add_model(model) 

set.seed(12222021)

boots <- bootstraps(train, times = 100, apparent = TRUE)
head(boots)

set.seed(12222021)

model_fit_cv <- fit_resamples(object = flow,
                           resamples = boots,
                           control = control_resamples(verbose = TRUE,
                                                  save_pred = TRUE))

# model_fit_cv$.notes[[1]] %>% View()

head(model_fit_cv)

model_fit_cv <- model_fit_cv %>% 
  unnest(.metrics)

model_fit_cv %>% 
  filter(.metric == "rmse") %>% 
  ggplot(aes(.estimate)) + 
  geom_histogram(fill = "dodgerblue", color = "white", bins = 15)

model_fit_cv %>% 
  filter(.metric == "rmse") %>%
  arrange(.estimate) %>% 
  head(1)

model_fit_cv %>% 
  filter(.metric == "rsq") %>%
  arrange(desc(.estimate)) %>% 
  head(1)

best_model <- model_fit_cv %>% 
  filter(id == "Bootstrap039") 

boot39 <- boots %>% 
  filter(id == "Bootstrap039")

# best_model$.predictions[[1]]
# best_model$.predictions[[1]]$.pred
boot39 <- boot39$splits[[1]]$data

```



```{r}
baked_train <- recipe %>% 
  prep() %>% 
  bake(new_data = train)

set.seed(12222021)

boots_model <- boots %>% 
  mutate(model = map(splits, ~lm(non_passing_rate ~ year + department + enrollment + course_number + 
                   first_gen_enroll + non_first_gen_enroll + first_gen_gpa + not_first_gen_gpa +
                   gen_gpa_gap +
                   female_enroll + female_gpa + male_gpa + gender_gpa_gap + male_enroll +
                   latino_enroll + white_enroll + black_enroll + asian_enroll +
                   latino_gpa + white_gpa + black_gpa + asian_gpa +
                   term_type,
                   data = .x)),
         coef_info = map(model, tidy))

boots_model_un <- boots_model %>% 
  unnest(coef_info)

boots_model_un %>% 
  arrange(estimate) %>% 
  head()

model_fits <- boots_model %>% 
  sample_n(50) %>%
  mutate(augmented = map(model, augment)) %>%
  unnest(augmented)

model_fits %>% 
  ggplot(aes(not_first_gen_gpa, non_passing_rate, group = id)) + 
  geom_line(aes(y = .fitted, group = id), color = "dodgerblue") +
  geom_point(alpha = .5)

```

```{r}
set.seed(12222021)

# bootstrapped all data
recipe <- recipe(non_passing_rate ~ year + department + enrollment + course_number + 
                   first_gen_enroll + non_first_gen_enroll + first_gen_gpa + not_first_gen_gpa +
                   gen_gpa_gap +
                   female_enroll + female_gpa + male_gpa + gender_gpa_gap + male_enroll +
                   latino_enroll + white_enroll + black_enroll + asian_enroll +
                   latino_gpa + white_gpa + black_gpa + asian_gpa +
                   term_type,
                     data = academic) %>% 
  step_zv(all_predictors(), -all_outcomes()) %>% 
  step_unknown(all_nominal()) %>% 
  step_novel(all_nominal()) %>% 
  step_dummy(all_nominal()) %>% 
  step_nzv(all_predictors()) %>%
  step_impute_mean(all_numeric(), -all_outcomes()) %>% 
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_nzv(all_predictors()) %>% 
  prep(training = academic, retain = TRUE)

boots <- bootstraps(academic, times = 200, apparent = FALSE)
head(boots)

baked_train <- recipe %>% 
  prep() %>% 
  bake(new_data = academic)

set.seed(12222021)

boots_model <- boots %>% 
  mutate(model = map(splits, ~lm(non_passing_rate ~ year + department + enrollment + course_number + 
                   first_gen_enroll + non_first_gen_enroll + first_gen_gpa + not_first_gen_gpa +
                   gen_gpa_gap +
                   female_enroll + female_gpa + male_gpa + gender_gpa_gap + male_enroll +
                   latino_enroll + white_enroll + black_enroll + asian_enroll +
                   latino_gpa + white_gpa + black_gpa + asian_gpa +
                   term_type,
                   data = .x)),
         coef_info = map(model, tidy),
         augmented = map(model, augment),
         predictions = map(model, predict))

boots_model_un <- boots_model %>% 
  unnest(coef_info)

boots_model_un %>% 
  arrange(estimate) %>% 
  head(10) 
  # glimpse()
  # View()

set.seed(12222021)

model_fits <- boots_model %>%
  unnest(augmented)

model_fits$splits[[1]]$data
model_fits$predictions[[1]]

rmse_models <- model_fits %>% 
  mutate(rmse_value = map_dbl(predictions, ~sqrt(mean((non_passing_rate - .x)^2)))) 

rmse_models %>%  
  distinct(rmse_value) %>% 
  summarize(mean = mean(rmse_value))

model_fits %>% 
  ggplot(aes(gender_gpa_gap, non_passing_rate, group = id)) + 
  geom_line(aes(y = .fitted, group = id), color = "dodgerblue") +
  geom_point(alpha = .5)

model_fits %>% 
  ggplot(aes(male_gpa, non_passing_rate, group = id)) + 
  geom_line(aes(y = .fitted, group = id), color = "dodgerblue") +
  geom_point(alpha = .5)

```
